// AUTO-GENERATED by scripts/gen-build-info.js on every `npm run build` -
// do not hand-edit, your changes will be overwritten on the next build.
// Committed as a placeholder so the app still compiles before a first
// build has run (e.g. `ng serve` during local development).

export const BUILD_INFO = {
  /** Calendar-versioned build id (UTC) - string-comparable, so a newer
   * build is always alphabetically greater than an older one. */
  version: '2026.09.10-0611',
  /** Full ISO timestamp of this build, for a precise "built X ago". */
  builtAt: '2026-09-10T06:11:47.342Z',
};
